// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxombdqdwhrxhzriisbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4b21iZHFkd2hyeGh6cmlpc2JwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMzkzNjgsImV4cCI6MjA2ODgxNTM2OH0.4oYropTQR2ir0qmHMcvNMMzJMdUJNsNLSXRThR3Ishk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});